// ═══════════════════════════════════════════════════════════════════
// ACCESSORIES CATALOGUE (EN) — product list
// ───────────────────────────────────────────────────────────────────
// This is the English version of the full real-product catalogue
// (84 items) matching the photos in photo/aksesuari/products/.
// Products have no price shown — price can be requested via the
// request form (cart icon) on the catalogue page.
//
// When adding/changing a product, also update products.js (LV) and
// products.ru.js (RU) so the catalogue stays in sync across languages.
// ═══════════════════════════════════════════════════════════════════

window.SKAT_PRODUCTS = [
  // Handles
  {id:6,name:'Hoppe window handle, satin chrome/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0530_US952_F9_WEB.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: satin chrome/silver','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:7,name:'Hoppe window handle, white/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0700S_UD9020_F1_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a built-in key lock — extra security against unauthorised opening. Suits PVC and aluminium window profiles.',features:['Colour/finish: white/silver','With key lock','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:8,name:'Hoppe window handle, satin chrome/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0700S_UD9020_F9_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a built-in key lock — extra security against unauthorised opening. Suits PVC and aluminium window profiles.',features:['Colour/finish: satin chrome/silver','With key lock','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:9,name:'Hoppe window handle, satin chrome/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0700_UD9020_F1_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: satin chrome/silver','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:10,name:'Hoppe window handle, polished gold/brass',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0700_UD9020_F4_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: polished gold/brass','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:11,name:'Hoppe window handle, white (RAL 9016)',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0700_UD9020_F9016_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: white (RAL 9016)','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:12,name:'Hoppe window handle, anthracite/black (RAL 7016)',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0700_UD9020_F9714_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: anthracite/black (RAL 7016)','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:13,name:'Hoppe window handle, satin chrome/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0700_UD9020_F9_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: satin chrome/silver','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:14,name:'Hoppe window handle, matte black',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710LVK_U71Z_melns_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: matte black','Hand: left-hand','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:15,name:'Hoppe window handle, black',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710LVK_U71Z_melns_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: black','Hand: right-hand','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:18,name:'FKS window handle, white',brand:'FKS',cat:'rokturi',img:'../photo/aksesuari/products/1005%20A-38%20bal_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a built-in key lock — extra security against unauthorised opening. Suits PVC and aluminium window profiles.',features:['Colour/finish: white','With key lock','Brand: FKS','Suits PVC and aluminium windows']},
  {id:19,name:'FKS window handle, brown',brand:'FKS',cat:'rokturi',img:'../photo/aksesuari/products/1005-32%20br_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: brown','Brand: FKS','Suits PVC and aluminium windows']},
  {id:20,name:'FKS window handle, white',brand:'FKS',cat:'rokturi',img:'../photo/aksesuari/products/1005-38_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: white','Brand: FKS','Suits PVC and aluminium windows']},
  {id:21,name:'FKS window handle, anthracite (RAL 7016)',brand:'FKS',cat:'rokturi',img:'../photo/aksesuari/products/1005-43%20Ral%207016_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: anthracite (RAL 7016)','Brand: FKS','Suits PVC and aluminium windows']},
  {id:26,name:'Hoppe window handle, satin chrome/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/10726825_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a slot for a cylinder insert for extra locking. Suits PVC and aluminium window profiles.',features:['Colour/finish: satin chrome/silver','With cylinder slot','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:27,name:'Hoppe window handle, satin chrome/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/10764792_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a built-in key lock — extra security against unauthorised opening. Suits PVC and aluminium window profiles.',features:['Colour/finish: satin chrome/silver','With key lock','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:28,name:'Door pull handle set, anthracite/dark grey',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/11470163004_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A pair of pull handles (outside and inside) for entrance or interior doors. No lock mechanism — handle function only.',features:['Colour: anthracite/dark grey','Includes: 2 handles + screws','No lock mechanism','Suits entrance and interior doors']},
  {id:29,name:'Door pull handle set, dark brown',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/11480193002_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A pair of pull handles (outside and inside) for entrance or interior doors. No lock mechanism — handle function only.',features:['Colour: dark brown','Includes: 2 handles + screws','No lock mechanism','Suits entrance and interior doors']},
  {id:30,name:'Door pull handle set, dark brown/white',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/114801990163001_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A pair of pull handles (outside and inside) for entrance or interior doors. No lock mechanism — handle function only.',features:['Colour: dark brown/white','Includes: 2 handles + screws','No lock mechanism','Suits entrance and interior doors']},
  {id:31,name:'Door pull handle set, black',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/11490053001_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A pair of pull handles (outside and inside) for entrance or interior doors. No lock mechanism — handle function only.',features:['Colour: black','Includes: 2 handles + screws','No lock mechanism','Suits entrance and interior doors']},
  {id:32,name:'Door pull handle set, black',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/11490053004_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A pair of pull handles (outside and inside) for entrance or interior doors. No lock mechanism — handle function only.',features:['Colour: black','Includes: 2 handles + screws','No lock mechanism','Suits entrance and interior doors']},
  {id:33,name:'Door pull handle set, white',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/11490163001_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A pair of pull handles (outside and inside) for entrance or interior doors. No lock mechanism — handle function only.',features:['Colour: white','Includes: 2 handles + screws','No lock mechanism','Suits entrance and interior doors']},
  {id:34,name:'Door pull handle set, white',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/11490163004_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A pair of pull handles (outside and inside) for entrance or interior doors. No lock mechanism — handle function only.',features:['Colour: white','Includes: 2 handles + screws','No lock mechanism','Suits entrance and interior doors']},
  {id:35,name:'window handle, silver/aluminium',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/11519265EN.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: silver/aluminium','Suits PVC and aluminium windows']},
  {id:36,name:'Hoppe door handle set with WC lock, anthracite/dark grey (matte)',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11618358_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Interior door handle set with a built-in WC/bathroom turn-release lock. Suitable for bathroom and toilet doors.',features:['Finish: anthracite/dark grey (matte)','WC turn-release lock','Includes: 2 handles + roses','Suits bathroom/toilet doors','Brand: Hoppe']},
  {id:38,name:'Hoppe door handle set with WC lock, copper/rose-gold (brushed bronze)',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11717495_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Interior door handle set with a built-in WC/bathroom turn-release lock. Suitable for bathroom and toilet doors.',features:['Finish: copper/rose-gold (brushed bronze)','WC turn-release lock','Includes: 2 handles + roses','Suits bathroom/toilet doors','Brand: Hoppe']},
  {id:39,name:'Hoppe window handle, silver/aluminium',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11736689_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a built-in key lock — extra security against unauthorised opening. Suits PVC and aluminium window profiles.',features:['Colour/finish: silver/aluminium','With key lock','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:40,name:'Hoppe window handle, silver/aluminium',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11736975_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a slot for a cylinder insert for extra locking. Suits PVC and aluminium window profiles.',features:['Colour/finish: silver/aluminium','With cylinder slot','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:41,name:'Hoppe window handle, silver/aluminium',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11739812_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: silver/aluminium','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:42,name:'Hoppe window handle, black/anthracite',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11750261_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a slot for a cylinder insert for extra locking. Suits PVC and aluminium window profiles.',features:['Colour/finish: black/anthracite','With cylinder slot','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:43,name:'Hoppe window handle, silver/satin chrome',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11752191_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a built-in key lock — extra security against unauthorised opening. Suits PVC and aluminium window profiles.',features:['Colour/finish: silver/satin chrome','With key lock','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:44,name:'Hoppe window handle, silver/satin chrome',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11752221_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a slot for a cylinder insert for extra locking. Suits PVC and aluminium window profiles.',features:['Colour/finish: silver/satin chrome','With cylinder slot','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:45,name:'Hoppe window handle, silver/satin chrome',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11752233_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: silver/satin chrome','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:46,name:'Hoppe window handle, silver/satin chrome',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11752373_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a slot for a cylinder insert for extra locking. Suits PVC and aluminium window profiles.',features:['Colour/finish: silver/satin chrome','With cylinder slot','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:47,name:'Hoppe window handle, silver/satin chrome',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11752385_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: silver/satin chrome','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:48,name:'Hoppe window handle, silver/satin chrome',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11752403_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: silver/satin chrome','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:51,name:'Hoppe door handle set with WC lock, black/anthracite (matte)',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11758223_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Interior door handle set with a built-in WC/bathroom turn-release lock. Suitable for bathroom and toilet doors.',features:['Finish: black/anthracite (matte)','WC turn-release lock','Includes: 2 handles + roses','Suits bathroom/toilet doors','Brand: Hoppe']},
  {id:52,name:'Hoppe door handle set with WC lock, silver/satin chrome',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11758235_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Interior door handle set with a built-in WC/bathroom turn-release lock. Suitable for bathroom and toilet doors.',features:['Finish: silver/satin chrome','WC turn-release lock','Includes: 2 handles + roses','Suits bathroom/toilet doors','Brand: Hoppe']},
  {id:73,name:'Fab&Fix Connoisseur window handle, white (left-hand)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_balts_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" range espagnolette-style window handle with an integrated key lock. Suits timber and PVC windows, 168 mm length.',features:['Finish: white','Hand: left-hand','Key lock included','Length: 168 mm','Suits timber and PVC windows']},
  {id:74,name:'Fab&Fix Connoisseur window handle, white (right-hand)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_balts_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" range espagnolette-style window handle with an integrated key lock. Suits timber and PVC windows, 168 mm length.',features:['Finish: white','Hand: right-hand','Key lock included','Length: 168 mm','Suits timber and PVC windows']},
  {id:75,name:'Fab&Fix Connoisseur window handle, matte chrome (left-hand)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_matets_hroms_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" range espagnolette-style window handle with an integrated key lock. Suits timber and PVC windows, 168 mm length.',features:['Finish: matte chrome','Hand: left-hand','Key lock included','Length: 168 mm','Suits timber and PVC windows']},
  {id:76,name:'Fab&Fix Connoisseur window handle, matte chrome (left-hand)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_matets_hroms_kreisais_web1.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" range espagnolette-style window handle with an integrated key lock. Suits timber and PVC windows, 168 mm length.',features:['Finish: matte chrome','Hand: left-hand','Key lock included','Length: 168 mm','Suits timber and PVC windows']},
  {id:77,name:'Fab&Fix Connoisseur window handle, polished chrome (left-hand)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_pulets_hroms_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" range espagnolette-style window handle with an integrated key lock. Suits timber and PVC windows, 168 mm length.',features:['Finish: polished chrome','Hand: left-hand','Key lock included','Length: 168 mm','Suits timber and PVC windows']},
  {id:78,name:'Fab&Fix Connoisseur window handle, polished chrome (left-hand)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_pulets_hroms_kreisais_web1.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" range espagnolette-style window handle with an integrated key lock. Suits timber and PVC windows, 168 mm length.',features:['Finish: polished chrome','Hand: left-hand','Key lock included','Length: 168 mm','Suits timber and PVC windows']},
  {id:79,name:'Fab&Fix Connoisseur window handle, polished chrome (right-hand)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_pulets_hroms_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" range espagnolette-style window handle with an integrated key lock. Suits timber and PVC windows, 168 mm length.',features:['Finish: polished chrome','Hand: right-hand','Key lock included','Length: 168 mm','Suits timber and PVC windows']},
  {id:80,name:'Fab&Fix Connoisseur window handle, polished chrome (right-hand)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_pulets_hroms_labais_web1.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" range espagnolette-style window handle with an integrated key lock. Suits timber and PVC windows, 168 mm length.',features:['Finish: polished chrome','Hand: right-hand','Key lock included','Length: 168 mm','Suits timber and PVC windows']},
  {id:81,name:'Fab&Fix Connoisseur window handle, polished gold (right-hand)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_pulets_zelts_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" range espagnolette-style window handle with an integrated key lock. Suits timber and PVC windows, 168 mm length.',features:['Finish: polished gold','Hand: right-hand','Key lock included','Length: 168 mm','Suits timber and PVC windows']},
  {id:82,name:'Fab&Fix Connoisseur window handle, dark bronze (left-hand)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_tumsa_bronza_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" range espagnolette-style window handle with an integrated key lock. Suits timber and PVC windows, 168 mm length.',features:['Finish: dark bronze','Hand: left-hand','Key lock included','Length: 168 mm','Suits timber and PVC windows']},
  {id:83,name:'Fab&Fix Connoisseur window handle, dark bronze (right-hand)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_tumsa_bronza_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" range espagnolette-style window handle with an integrated key lock. Suits timber and PVC windows, 168 mm length.',features:['Finish: dark bronze','Hand: right-hand','Key lock included','Length: 168 mm','Suits timber and PVC windows']},
  {id:84,name:'Fab&Fix Connoisseur window handle, dark bronze (right-hand)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_tumsa_bronza_labais_web2.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" range espagnolette-style window handle with an integrated key lock. Suits timber and PVC windows, 168 mm length.',features:['Finish: dark bronze','Hand: right-hand','Key lock included','Length: 168 mm','Suits timber and PVC windows']},
  {id:85,name:'Hoppe window handle, titanium',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0600S_US952_titans_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a built-in key lock — extra security against unauthorised opening. Suits PVC and aluminium window profiles.',features:['Colour/finish: titanium','With key lock','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:86,name:'Hoppe window handle, anthracite',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0600_US952_antracits_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: anthracite','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:87,name:'Hoppe window handle, white',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0600_US952_balts_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: white','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:88,name:'Hoppe window handle, black',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0600_US952_melns_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: black','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:89,name:'Hoppe window handle, chrome/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710EVKS_6_F1_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a built-in key lock — extra security against unauthorised opening. Suits PVC and aluminium window profiles.',features:['Colour/finish: chrome/silver','Hand: right-hand','With key lock','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:90,name:'Hoppe window handle, satin chrome/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710LVK_U71Z_F1_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: satin chrome/silver','Hand: left-hand','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:91,name:'Hoppe window handle, satin chrome/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710LVK_U71Z_F1_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: satin chrome/silver','Hand: right-hand','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:92,name:'Hoppe window handle, satin chrome/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710LVK_U71Z_F9_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: satin chrome/silver','Hand: left-hand','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:93,name:'Hoppe window handle, white',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710LVK_U71Z_balts_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: white','Hand: left-hand','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:94,name:'Hoppe window handle, white',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710LVK_U71Z_balts_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A classic window handle for opening and ventilating. Suits PVC and aluminium window profiles with standard fixing.',features:['Colour/finish: white','Hand: right-hand','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:95,name:'Hoppe window handle with security catch, satin chrome/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710SV_U26_F1_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a built-in security catch against lifting and unauthorised opening (no key). Suits PVC and aluminium window profiles.',features:['Colour/finish: satin chrome/silver','With security catch (no key)','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:96,name:'Hoppe window handle, satin chrome/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710VK_93S_F1_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a slot for a cylinder insert for extra locking. Suits PVC and aluminium window profiles.',features:['Colour/finish: satin chrome/silver','Hand: left-hand','With cylinder slot','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:97,name:'Hoppe window handle, satin chrome/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710VK_93S_F1_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a slot for a cylinder insert for extra locking. Suits PVC and aluminium window profiles.',features:['Colour/finish: satin chrome/silver','Hand: right-hand','With cylinder slot','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:98,name:'Hoppe window handle, satin chrome/silver',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710VK_93S_F9_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Window handle with a slot for a cylinder insert for extra locking. Suits PVC and aluminium window profiles.',features:['Colour/finish: satin chrome/silver','Hand: right-hand','With cylinder slot','Brand: Hoppe','Suits PVC and aluminium windows']},
  {id:99,name:'Hoppe door handle set with cylinder cutout, copper/rose-gold (brushed bronze)',brand:'Hoppe',cat:'sledzenes',img:'../photo/aksesuari/products/11843391_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Door handle set with a euro-cylinder cutout — suitable for entrance doors fitted with a key lock. Includes both handles and fixing screws.',features:['Finish: copper/rose-gold (brushed bronze)','Euro-cylinder cutout','Includes: 2 handles + screws','Suitable for entrance doors','Brand: Hoppe']},
  {id:100,name:'Hoppe door handle set with WC lock, dark bronze',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11843408_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Interior door handle set with a built-in WC/bathroom turn-release lock. Suitable for bathroom and toilet doors.',features:['Finish: dark bronze','WC turn-release lock','Includes: 2 handles + roses','Suits bathroom/toilet doors','Brand: Hoppe']},
  {id:101,name:'Hoppe door handle set, satin chrome/inox',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11894477_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'A pair of handles (outside and inside) for entrance or interior doors. No lock mechanism — handle function only.',features:['Colour: satin chrome/inox','Includes: 2 handles + screws','No lock mechanism','Suits entrance and interior doors','Brand: Hoppe']},
  {id:102,name:'Hoppe door handle set with cylinder cutout, black (matte)',brand:'Hoppe',cat:'sledzenes',img:'../photo/aksesuari/products/11907939_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Door handle set with a euro-cylinder cutout — suitable for entrance doors fitted with a key lock. Includes both handles and fixing screws.',features:['Finish: black (matte)','Euro-cylinder cutout','Includes: 2 handles + screws','Suitable for entrance doors','Brand: Hoppe']},
  {id:103,name:'Hoppe door handle set with cylinder cutout, matte gold/brass',brand:'Hoppe',cat:'sledzenes',img:'../photo/aksesuari/products/11908531_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Door handle set with a euro-cylinder cutout — suitable for entrance doors fitted with a key lock. Includes both handles and fixing screws.',features:['Finish: matte gold/brass','Euro-cylinder cutout','Includes: 2 handles + screws','Suitable for entrance doors','Brand: Hoppe']},
  {id:104,name:'Hoppe door handle set with WC lock, matte gold/brass',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11908609_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Interior door handle set with a built-in WC/bathroom turn-release lock. Suitable for bathroom and toilet doors.',features:['Finish: matte gold/brass','WC turn-release lock','Includes: 2 handles + roses','Suits bathroom/toilet doors','Brand: Hoppe']},

  // Locks
  {id:16,name:'Fab&Fix door handle with key lock, satin chrome/silver',brand:'Fab&Fix',cat:'sledzenes',img:'../photo/aksesuari/products/0D200_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Espagnolette-style door handle with an integrated key lock for operating a multi-point locking mechanism. Length 168 mm.',features:['Finish: satin chrome/silver','Key lock included','Length: 168 mm','Operates multi-point locking mechanism']},
  {id:17,name:'Fab&Fix door handle with key lock, satin grey (anodised aluminium)',brand:'Fab&Fix',cat:'sledzenes',img:'../photo/aksesuari/products/0D201_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Espagnolette-style door handle with an integrated key lock for operating a multi-point locking mechanism. Length 168 mm.',features:['Finish: satin grey (anodised aluminium)','Key lock included','Length: 168 mm','Operates multi-point locking mechanism']},
  {id:22,name:'FKS door handle set with cylinder cutout, anthracite/black (RAL 7016)',brand:'FKS',cat:'sledzenes',img:'../photo/aksesuari/products/1005B%20Ral%207016_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Door handle set with a euro-cylinder cutout — suitable for entrance doors fitted with a key lock. Includes both handles and fixing screws.',features:['Finish: anthracite/black (RAL 7016)','Euro-cylinder cutout','Includes: 2 handles + screws','Suitable for entrance doors','Brand: FKS']},
  {id:23,name:'FKS door handle set with cylinder cutout, white/brown',brand:'FKS',cat:'sledzenes',img:'../photo/aksesuari/products/1005B%20bal_bru_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Door handle set with a euro-cylinder cutout — suitable for entrance doors fitted with a key lock. Includes both handles and fixing screws.',features:['Finish: white/brown','Euro-cylinder cutout','Includes: 2 handles + screws','Suitable for entrance doors','Brand: FKS']},
  {id:24,name:'FKS door handle set with cylinder cutout, white',brand:'FKS',cat:'sledzenes',img:'../photo/aksesuari/products/1005B%20bal_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Door handle set with a euro-cylinder cutout — suitable for entrance doors fitted with a key lock. Includes both handles and fixing screws.',features:['Finish: white','Euro-cylinder cutout','Includes: 2 handles + screws','Suitable for entrance doors','Brand: FKS']},
  {id:25,name:'FKS door handle set with cylinder cutout, brown',brand:'FKS',cat:'sledzenes',img:'../photo/aksesuari/products/1005B%20br_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Door handle set with a euro-cylinder cutout — suitable for entrance doors fitted with a key lock. Includes both handles and fixing screws.',features:['Finish: brown','Euro-cylinder cutout','Includes: 2 handles + screws','Suitable for entrance doors','Brand: FKS']},
  {id:37,name:'Hoppe door handle set with cylinder cutout, copper/rose-gold (brushed bronze)',brand:'Hoppe',cat:'sledzenes',img:'../photo/aksesuari/products/11647589_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Door handle set with a euro-cylinder cutout — suitable for entrance doors fitted with a key lock. Includes both handles and fixing screws.',features:['Finish: copper/rose-gold (brushed bronze)','Euro-cylinder cutout','Includes: 2 handles + screws','Suitable for entrance doors','Brand: Hoppe']},
  {id:49,name:'Hoppe door handle set with cylinder cutout, silver/satin chrome',brand:'Hoppe',cat:'sledzenes',img:'../photo/aksesuari/products/11758156_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Door handle set with a euro-cylinder cutout — suitable for entrance doors fitted with a key lock. Includes both handles and fixing screws.',features:['Finish: silver/satin chrome','Euro-cylinder cutout','Includes: 2 handles + screws','Suitable for entrance doors','Brand: Hoppe']},
  {id:50,name:'Hoppe door handle set with cylinder cutout, black/anthracite (matte)',brand:'Hoppe',cat:'sledzenes',img:'../photo/aksesuari/products/11758168_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Door handle set with a euro-cylinder cutout — suitable for entrance doors fitted with a key lock. Includes both handles and fixing screws.',features:['Finish: black/anthracite (matte)','Euro-cylinder cutout','Includes: 2 handles + screws','Suitable for entrance doors','Brand: Hoppe']},
  {id:70,name:'Hermai door handle set with cylinder cutout, satin chrome/stainless steel',brand:'Hermai',cat:'sledzenes',img:'../photo/aksesuari/products/SICHL.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Door handle set with a euro-cylinder cutout — suitable for entrance doors fitted with a key lock. Includes both handles and fixing screws.',features:['Finish: satin chrome/stainless steel','Euro-cylinder cutout','Includes: 2 handles + screws','Suitable for entrance doors','Brand: Hermai']},
  {id:71,name:'Hermai door handle set with cylinder cutout, satin chrome/brushed nickel',brand:'Hermai',cat:'sledzenes',img:'../photo/aksesuari/products/SICHR.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Door handle set with a euro-cylinder cutout — suitable for entrance doors fitted with a key lock. Includes both handles and fixing screws.',features:['Finish: satin chrome/brushed nickel','Euro-cylinder cutout','Includes: 2 handles + screws','Suitable for entrance doors','Brand: Hermai']},
  {id:72,name:'Hermai door handle set with cylinder cutout, polished gold/brass',brand:'Hermai',cat:'sledzenes',img:'../photo/aksesuari/products/SICZR.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Door handle set with a euro-cylinder cutout — suitable for entrance doors fitted with a key lock. Includes both handles and fixing screws.',features:['Finish: polished gold/brass','Euro-cylinder cutout','Includes: 2 handles + screws','Suitable for entrance doors','Brand: Hermai']},

  // Hinges
  {id:53,name:'greenteQ hinge cover cap, white',brand:'greenteQ',cat:'enges',img:'../photo/aksesuari/products/2172745859_web.jpg',bg:'#7b5e3a',icon:'enge',desc:'Decorative cap for covering a window or door hinge. Snaps into place, fixed with 2 screws.',features:['Colour: white','Size: 82×49×21 mm','Fixing: 2 screws','greenteQ (VBH) brand']},
  {id:54,name:'greenteQ hinge cover cap, black/anthracite',brand:'greenteQ',cat:'enges',img:'../photo/aksesuari/products/2172745861_web.jpg',bg:'#7b5e3a',icon:'enge',desc:'Decorative cap for covering a window or door hinge. Snaps into place, fixed with 2 screws.',features:['Colour: black/anthracite','Size: 82×49×21 mm','Fixing: 2 screws','greenteQ (VBH) brand']},
  {id:55,name:'greenteQ hinge cover cap, silver/aluminium',brand:'greenteQ',cat:'enges',img:'../photo/aksesuari/products/2172745863_web.jpg',bg:'#7b5e3a',icon:'enge',desc:'Decorative cap for covering a window or door hinge. Snaps into place, fixed with 2 screws.',features:['Colour: silver/aluminium','Size: 82×49×21 mm','Fixing: 2 screws','greenteQ (VBH) brand']},

  // Sealants
  {id:56,name:'Lakma sealant, colourless',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/Bezkrasains.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silicone sealant for sealing window and door installation joints. High UV and weather resistance, stays flexible once cured.',features:['Colour: colourless','Silicone sealant','UV and weather resistant','Made by Lakma']},
  {id:57,name:'Lakma sealant, colourless',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/Bezkrasains_280.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silicone sealant for sealing window and door installation joints. High UV and weather resistance, stays flexible once cured.',features:['Colour: colourless','Silicone sealant','UV and weather resistant','Made by Lakma']},
  {id:58,name:'Lakma sealant, beige (RAL 1011)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL1011.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silicone sealant for sealing window and door installation joints. High UV and weather resistance, stays flexible once cured.',features:['Colour: beige (RAL 1011)','Silicone sealant','UV and weather resistant','Made by Lakma']},
  {id:59,name:'Lakma sealant, ivory (RAL 1014)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL1014.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silicone sealant for sealing window and door installation joints. High UV and weather resistance, stays flexible once cured.',features:['Colour: ivory (RAL 1014)','Silicone sealant','UV and weather resistant','Made by Lakma']},
  {id:60,name:'Lakma sealant, anthracite grey (RAL 7016)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL7016.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silicone sealant for sealing window and door installation joints. High UV and weather resistance, stays flexible once cured.',features:['Colour: anthracite grey (RAL 7016)','Silicone sealant','UV and weather resistant','Made by Lakma']},
  {id:61,name:'Lakma sealant, dusty grey (RAL 7037)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL7037.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silicone sealant for sealing window and door installation joints. High UV and weather resistance, stays flexible once cured.',features:['Colour: dusty grey (RAL 7037)','Silicone sealant','UV and weather resistant','Made by Lakma']},
  {id:62,name:'Lakma sealant, window grey (RAL 7040)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL7040.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silicone sealant for sealing window and door installation joints. High UV and weather resistance, stays flexible once cured.',features:['Colour: window grey (RAL 7040)','Silicone sealant','UV and weather resistant','Made by Lakma']},
  {id:63,name:'Lakma sealant, ochre brown (RAL 8001)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL8001.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silicone sealant for sealing window and door installation joints. High UV and weather resistance, stays flexible once cured.',features:['Colour: ochre brown (RAL 8001)','Silicone sealant','UV and weather resistant','Made by Lakma']},
  {id:64,name:'Lakma sealant, clay brown (RAL 8003)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL8003.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silicone sealant for sealing window and door installation joints. High UV and weather resistance, stays flexible once cured.',features:['Colour: clay brown (RAL 8003)','Silicone sealant','UV and weather resistant','Made by Lakma']},
  {id:65,name:'Lakma sealant, nut brown (RAL 8011)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL8011.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silicone sealant for sealing window and door installation joints. High UV and weather resistance, stays flexible once cured.',features:['Colour: nut brown (RAL 8011)','Silicone sealant','UV and weather resistant','Made by Lakma']},
  {id:66,name:'Lakma sealant, chestnut brown (RAL 8015)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL8015.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silicone sealant for sealing window and door installation joints. High UV and weather resistance, stays flexible once cured.',features:['Colour: chestnut brown (RAL 8015)','Silicone sealant','UV and weather resistant','Made by Lakma']},
  {id:67,name:'Lakma sealant, chocolate brown (RAL 8017)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL8017.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silicone sealant for sealing window and door installation joints. High UV and weather resistance, stays flexible once cured.',features:['Colour: chocolate brown (RAL 8017)','Silicone sealant','UV and weather resistant','Made by Lakma']},
  {id:68,name:'Lakma sealant, grey-brown (RAL 8019)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL8019.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silicone sealant for sealing window and door installation joints. High UV and weather resistance, stays flexible once cured.',features:['Colour: grey-brown (RAL 8019)','Silicone sealant','UV and weather resistant','Made by Lakma']},
  {id:69,name:'Lakma sealant, jet black (RAL 9005)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL9005.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silicone sealant for sealing window and door installation joints. High UV and weather resistance, stays flexible once cured.',features:['Colour: jet black (RAL 9005)','Silicone sealant','UV and weather resistant','Made by Lakma']},

  // Maintenance
  {id:1,name:'Brevis trickle vent (white)',brand:'Brevis',cat:'apkope',img:'../photo/aksesuari/products/008064_web.jpg',bg:'#5a4a8a',icon:'apkope',desc:'Window trickle vent with a sliding cover and rotary adjustment mechanism for fresh-air inflow. Fits into the window frame without compromising thermal insulation.',features:['Length ~395 mm, slot ~345 mm','Colour: white','Adjustable via rotary handle','Suits PVC and aluminium window profiles']},
  {id:2,name:'Brevis trickle vent (brown)',brand:'Brevis',cat:'apkope',img:'../photo/aksesuari/products/008065_web.jpg',bg:'#5a4a8a',icon:'apkope',desc:'Window trickle vent with a sliding cover and rotary adjustment mechanism for fresh-air inflow. Fits into the window frame without compromising thermal insulation.',features:['Length ~395 mm, slot ~345 mm','Colour: brown','Adjustable via rotary handle','Suits PVC and aluminium window profiles']},
  {id:3,name:'Brevis trickle vent (dark brown)',brand:'Brevis',cat:'apkope',img:'../photo/aksesuari/products/008066_web.jpg',bg:'#5a4a8a',icon:'apkope',desc:'Window trickle vent with a sliding cover and rotary adjustment mechanism for fresh-air inflow. Fits into the window frame without compromising thermal insulation.',features:['Length ~395 mm, slot ~345 mm','Colour: dark brown','Adjustable via rotary handle','Suits PVC and aluminium window profiles']},
  {id:4,name:'Brevis trickle vent (anthracite/grey-black)',brand:'Brevis',cat:'apkope',img:'../photo/aksesuari/products/024709_web.jpg',bg:'#5a4a8a',icon:'apkope',desc:'Window trickle vent with a sliding cover and rotary adjustment mechanism for fresh-air inflow. Fits into the window frame without compromising thermal insulation.',features:['Length ~395 mm, slot ~345 mm','Colour: anthracite/grey-black','Adjustable via rotary handle','Suits PVC and aluminium window profiles']},
  {id:5,name:'Brevis trickle vent (brown/copper)',brand:'Brevis',cat:'apkope',img:'../photo/aksesuari/products/032309_web.jpg',bg:'#5a4a8a',icon:'apkope',desc:'Window trickle vent with a sliding cover and rotary adjustment mechanism for fresh-air inflow. Fits into the window frame without compromising thermal insulation.',features:['Length ~395 mm, slot ~345 mm','Colour: brown/copper','Adjustable via rotary handle','Suits PVC and aluminium window profiles']}

];
