// ═══════════════════════════════════════════════════════════════════
// AKSESUĀRU KATALOGS — produktu saraksts
// ───────────────────────────────────────────────────────────────────
// Šis ir pilns reālo aksesuāru katalogs (84 produkti), kas atbilst
// fotoattēliem mapē photo/aksesuari/products/. Produktiem nav norādītas
// cenas — informāciju par cenu lūdzam pieprasīt, izmantojot pieprasījuma
// formu (groza ikonu) kataloga lapā.
//
// Lai pievienotu JAUNU PRODUKTU, nokopējiet vienu {…} bloku zemāk,
// nomainiet id (unikāls skaitlis) un aizpildiet pārējos laukus.
// Atjauninot šo failu, lūdzu atjauniniet arī products.ru.js un
// products.en.js, lai katalogs sakristu visās 3 valodās.
// ═══════════════════════════════════════════════════════════════════

window.SKAT_PRODUCTS = [
  // Rokturi
  {id:6,name:'Hoppe loga rokturis, matēts hroms/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0530_US952_F9_WEB.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: matēts hroms/sudrabs','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:7,name:'Hoppe loga rokturis, balts/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0700S_UD9020_F1_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar iebūvētu atslēgas slēdzeni — papildu drošība pret nesankcionētu loga atvēršanu. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: balts/sudrabs','Ar atslēgas slēdzeni','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:8,name:'Hoppe loga rokturis, matēts hroms/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0700S_UD9020_F9_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar iebūvētu atslēgas slēdzeni — papildu drošība pret nesankcionētu loga atvēršanu. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: matēts hroms/sudrabs','Ar atslēgas slēdzeni','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:9,name:'Hoppe loga rokturis, matēts hroms/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0700_UD9020_F1_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: matēts hroms/sudrabs','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:10,name:'Hoppe loga rokturis, pulēts zelts/misiņš',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0700_UD9020_F4_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: pulēts zelts/misiņš','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:11,name:'Hoppe loga rokturis, balts (RAL 9016)',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0700_UD9020_F9016_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: balts (RAL 9016)','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:12,name:'Hoppe loga rokturis, antracīts/melns (RAL 7016)',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0700_UD9020_F9714_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: antracīts/melns (RAL 7016)','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:13,name:'Hoppe loga rokturis, matēts hroms/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0700_UD9020_F9_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: matēts hroms/sudrabs','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:14,name:'Hoppe loga rokturis, melns (matēts)',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710LVK_U71Z_melns_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: melns (matēts)','Puse: kreisais','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:15,name:'Hoppe loga rokturis, melns',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710LVK_U71Z_melns_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: melns','Puse: labais','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:18,name:'FKS loga rokturis, balts',brand:'FKS',cat:'rokturi',img:'../photo/aksesuari/products/1005%20A-38%20bal_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar iebūvētu atslēgas slēdzeni — papildu drošība pret nesankcionētu loga atvēršanu. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: balts','Ar atslēgas slēdzeni','Zīmols: FKS','Piemērots PVC un ALU logiem']},
  {id:19,name:'FKS loga rokturis, brūns',brand:'FKS',cat:'rokturi',img:'../photo/aksesuari/products/1005-32%20br_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: brūns','Zīmols: FKS','Piemērots PVC un ALU logiem']},
  {id:20,name:'FKS loga rokturis, balts',brand:'FKS',cat:'rokturi',img:'../photo/aksesuari/products/1005-38_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: balts','Zīmols: FKS','Piemērots PVC un ALU logiem']},
  {id:21,name:'FKS loga rokturis, antracīts (RAL 7016)',brand:'FKS',cat:'rokturi',img:'../photo/aksesuari/products/1005-43%20Ral%207016_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: antracīts (RAL 7016)','Zīmols: FKS','Piemērots PVC un ALU logiem']},
  {id:26,name:'Hoppe loga rokturis, matēts hroms/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/10726825_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar vietu cilindra ieliktnim papildu fiksācijai. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: matēts hroms/sudrabs','Ar vietu cilindra ieliktnim','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:27,name:'Hoppe loga rokturis, matēts hroms/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/10764792_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar iebūvētu atslēgas slēdzeni — papildu drošība pret nesankcionētu loga atvēršanu. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: matēts hroms/sudrabs','Ar atslēgas slēdzeni','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:28,name:'Durvju roktura komplekts, antracīts/tumši pelēks',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/11470163004_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Durvju roktura pāris (ārpusei un iekšpusei) ārdurvīm vai iekšdurvīm. Bez slēdzenes mehānisma — tikai roktura funkcija.',features:['Krāsa: antracīts/tumši pelēks','Komplektā: 2 rokturi + skrūves','Bez slēdzenes mehānisma','Piemērots ārdurvīm un iekšdurvīm']},
  {id:29,name:'Durvju roktura komplekts, tumši brūns',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/11480193002_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Durvju roktura pāris (ārpusei un iekšpusei) ārdurvīm vai iekšdurvīm. Bez slēdzenes mehānisma — tikai roktura funkcija.',features:['Krāsa: tumši brūns','Komplektā: 2 rokturi + skrūves','Bez slēdzenes mehānisma','Piemērots ārdurvīm un iekšdurvīm']},
  {id:30,name:'Durvju roktura komplekts, tumši brūns/balts',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/114801990163001_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Durvju roktura pāris (ārpusei un iekšpusei) ārdurvīm vai iekšdurvīm. Bez slēdzenes mehānisma — tikai roktura funkcija.',features:['Krāsa: tumši brūns/balts','Komplektā: 2 rokturi + skrūves','Bez slēdzenes mehānisma','Piemērots ārdurvīm un iekšdurvīm']},
  {id:31,name:'Durvju roktura komplekts, melns',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/11490053001_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Durvju roktura pāris (ārpusei un iekšpusei) ārdurvīm vai iekšdurvīm. Bez slēdzenes mehānisma — tikai roktura funkcija.',features:['Krāsa: melns','Komplektā: 2 rokturi + skrūves','Bez slēdzenes mehānisma','Piemērots ārdurvīm un iekšdurvīm']},
  {id:32,name:'Durvju roktura komplekts, melns',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/11490053004_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Durvju roktura pāris (ārpusei un iekšpusei) ārdurvīm vai iekšdurvīm. Bez slēdzenes mehānisma — tikai roktura funkcija.',features:['Krāsa: melns','Komplektā: 2 rokturi + skrūves','Bez slēdzenes mehānisma','Piemērots ārdurvīm un iekšdurvīm']},
  {id:33,name:'Durvju roktura komplekts, balts',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/11490163001_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Durvju roktura pāris (ārpusei un iekšpusei) ārdurvīm vai iekšdurvīm. Bez slēdzenes mehānisma — tikai roktura funkcija.',features:['Krāsa: balts','Komplektā: 2 rokturi + skrūves','Bez slēdzenes mehānisma','Piemērots ārdurvīm un iekšdurvīm']},
  {id:34,name:'Durvju roktura komplekts, balts',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/11490163004_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Durvju roktura pāris (ārpusei un iekšpusei) ārdurvīm vai iekšdurvīm. Bez slēdzenes mehānisma — tikai roktura funkcija.',features:['Krāsa: balts','Komplektā: 2 rokturi + skrūves','Bez slēdzenes mehānisma','Piemērots ārdurvīm un iekšdurvīm']},
  {id:35,name:'loga rokturis, sudrabs/alumīnijs',brand:'',cat:'rokturi',img:'../photo/aksesuari/products/11519265EN.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: sudrabs/alumīnijs','Piemērots PVC un ALU logiem']},
  {id:36,name:'Hoppe durvju roktura komplekts ar WC fiksatoru, antracīts/tumši pelēks (matēts)',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11618358_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Iekšdurvju roktura komplekts ar iebūvētu griežamo WC/vannas istabas fiksatoru. Piemērots vannas istabas un tualetes durvīm.',features:['Apdare: antracīts/tumši pelēks (matēts)','Ar WC fiksatoru','Komplektā: 2 rokturi + rozetes','Piemērots vannas/tualetes durvīm','Zīmols: Hoppe']},
  {id:38,name:'Hoppe durvju roktura komplekts ar WC fiksatoru, vara/rozezelts (matēta bronza)',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11717495_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Iekšdurvju roktura komplekts ar iebūvētu griežamo WC/vannas istabas fiksatoru. Piemērots vannas istabas un tualetes durvīm.',features:['Apdare: vara/rozezelts (matēta bronza)','Ar WC fiksatoru','Komplektā: 2 rokturi + rozetes','Piemērots vannas/tualetes durvīm','Zīmols: Hoppe']},
  {id:39,name:'Hoppe loga rokturis, sudrabs/alumīnijs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11736689_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar iebūvētu atslēgas slēdzeni — papildu drošība pret nesankcionētu loga atvēršanu. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: sudrabs/alumīnijs','Ar atslēgas slēdzeni','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:40,name:'Hoppe loga rokturis, sudrabs/alumīnijs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11736975_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar vietu cilindra ieliktnim papildu fiksācijai. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: sudrabs/alumīnijs','Ar vietu cilindra ieliktnim','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:41,name:'Hoppe loga rokturis, sudrabs/alumīnijs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11739812_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: sudrabs/alumīnijs','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:42,name:'Hoppe loga rokturis, melns/antracīts',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11750261_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar vietu cilindra ieliktnim papildu fiksācijai. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: melns/antracīts','Ar vietu cilindra ieliktnim','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:43,name:'Hoppe loga rokturis, sudrabs/matēts hroms',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11752191_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar iebūvētu atslēgas slēdzeni — papildu drošība pret nesankcionētu loga atvēršanu. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: sudrabs/matēts hroms','Ar atslēgas slēdzeni','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:44,name:'Hoppe loga rokturis, sudrabs/matēts hroms',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11752221_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar vietu cilindra ieliktnim papildu fiksācijai. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: sudrabs/matēts hroms','Ar vietu cilindra ieliktnim','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:45,name:'Hoppe loga rokturis, sudrabs/matēts hroms',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11752233_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: sudrabs/matēts hroms','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:46,name:'Hoppe loga rokturis, sudrabs/matēts hroms',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11752373_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar vietu cilindra ieliktnim papildu fiksācijai. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: sudrabs/matēts hroms','Ar vietu cilindra ieliktnim','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:47,name:'Hoppe loga rokturis, sudrabs/matēts hroms',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11752385_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: sudrabs/matēts hroms','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:48,name:'Hoppe loga rokturis, sudrabs/matēts hroms',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11752403_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: sudrabs/matēts hroms','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:51,name:'Hoppe durvju roktura komplekts ar WC fiksatoru, melns/antracīts (matēts)',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11758223_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Iekšdurvju roktura komplekts ar iebūvētu griežamo WC/vannas istabas fiksatoru. Piemērots vannas istabas un tualetes durvīm.',features:['Apdare: melns/antracīts (matēts)','Ar WC fiksatoru','Komplektā: 2 rokturi + rozetes','Piemērots vannas/tualetes durvīm','Zīmols: Hoppe']},
  {id:52,name:'Hoppe durvju roktura komplekts ar WC fiksatoru, sudrabs/matēts hroms',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11758235_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Iekšdurvju roktura komplekts ar iebūvētu griežamo WC/vannas istabas fiksatoru. Piemērots vannas istabas un tualetes durvīm.',features:['Apdare: sudrabs/matēts hroms','Ar WC fiksatoru','Komplektā: 2 rokturi + rozetes','Piemērots vannas/tualetes durvīm','Zīmols: Hoppe']},
  {id:73,name:'Fab&Fix Connoisseur loga rokturis, balts (kreisais)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_balts_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" sērijas espanjolešu tipa loga rokturis ar iebūvētu atslēgas slēdzeni. Piemērots koka un PVC logiem, garums 168 mm.',features:['Apdare: balts','Puse: kreisais','Ar atslēgas slēdzeni','Garums: 168 mm','Piemērots koka un PVC logiem']},
  {id:74,name:'Fab&Fix Connoisseur loga rokturis, balts (labais)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_balts_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" sērijas espanjolešu tipa loga rokturis ar iebūvētu atslēgas slēdzeni. Piemērots koka un PVC logiem, garums 168 mm.',features:['Apdare: balts','Puse: labais','Ar atslēgas slēdzeni','Garums: 168 mm','Piemērots koka un PVC logiem']},
  {id:75,name:'Fab&Fix Connoisseur loga rokturis, matēts hroms (kreisais)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_matets_hroms_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" sērijas espanjolešu tipa loga rokturis ar iebūvētu atslēgas slēdzeni. Piemērots koka un PVC logiem, garums 168 mm.',features:['Apdare: matēts hroms','Puse: kreisais','Ar atslēgas slēdzeni','Garums: 168 mm','Piemērots koka un PVC logiem']},
  {id:76,name:'Fab&Fix Connoisseur loga rokturis, matēts hroms (kreisais)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_matets_hroms_kreisais_web1.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" sērijas espanjolešu tipa loga rokturis ar iebūvētu atslēgas slēdzeni. Piemērots koka un PVC logiem, garums 168 mm.',features:['Apdare: matēts hroms','Puse: kreisais','Ar atslēgas slēdzeni','Garums: 168 mm','Piemērots koka un PVC logiem']},
  {id:77,name:'Fab&Fix Connoisseur loga rokturis, pulēts hroms (kreisais)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_pulets_hroms_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" sērijas espanjolešu tipa loga rokturis ar iebūvētu atslēgas slēdzeni. Piemērots koka un PVC logiem, garums 168 mm.',features:['Apdare: pulēts hroms','Puse: kreisais','Ar atslēgas slēdzeni','Garums: 168 mm','Piemērots koka un PVC logiem']},
  {id:78,name:'Fab&Fix Connoisseur loga rokturis, pulēts hroms (kreisais)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_pulets_hroms_kreisais_web1.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" sērijas espanjolešu tipa loga rokturis ar iebūvētu atslēgas slēdzeni. Piemērots koka un PVC logiem, garums 168 mm.',features:['Apdare: pulēts hroms','Puse: kreisais','Ar atslēgas slēdzeni','Garums: 168 mm','Piemērots koka un PVC logiem']},
  {id:79,name:'Fab&Fix Connoisseur loga rokturis, pulēts hroms (labais)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_pulets_hroms_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" sērijas espanjolešu tipa loga rokturis ar iebūvētu atslēgas slēdzeni. Piemērots koka un PVC logiem, garums 168 mm.',features:['Apdare: pulēts hroms','Puse: labais','Ar atslēgas slēdzeni','Garums: 168 mm','Piemērots koka un PVC logiem']},
  {id:80,name:'Fab&Fix Connoisseur loga rokturis, pulēts hroms (labais)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_pulets_hroms_labais_web1.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" sērijas espanjolešu tipa loga rokturis ar iebūvētu atslēgas slēdzeni. Piemērots koka un PVC logiem, garums 168 mm.',features:['Apdare: pulēts hroms','Puse: labais','Ar atslēgas slēdzeni','Garums: 168 mm','Piemērots koka un PVC logiem']},
  {id:81,name:'Fab&Fix Connoisseur loga rokturis, pulēts zelts (labais)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_pulets_zelts_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" sērijas espanjolešu tipa loga rokturis ar iebūvētu atslēgas slēdzeni. Piemērots koka un PVC logiem, garums 168 mm.',features:['Apdare: pulēts zelts','Puse: labais','Ar atslēgas slēdzeni','Garums: 168 mm','Piemērots koka un PVC logiem']},
  {id:82,name:'Fab&Fix Connoisseur loga rokturis, tumša bronza (kreisais)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_tumsa_bronza_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" sērijas espanjolešu tipa loga rokturis ar iebūvētu atslēgas slēdzeni. Piemērots koka un PVC logiem, garums 168 mm.',features:['Apdare: tumša bronza','Puse: kreisais','Ar atslēgas slēdzeni','Garums: 168 mm','Piemērots koka un PVC logiem']},
  {id:83,name:'Fab&Fix Connoisseur loga rokturis, tumša bronza (labais)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_tumsa_bronza_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" sērijas espanjolešu tipa loga rokturis ar iebūvētu atslēgas slēdzeni. Piemērots koka un PVC logiem, garums 168 mm.',features:['Apdare: tumša bronza','Puse: labais','Ar atslēgas slēdzeni','Garums: 168 mm','Piemērots koka un PVC logiem']},
  {id:84,name:'Fab&Fix Connoisseur loga rokturis, tumša bronza (labais)',brand:'Fab&Fix',cat:'rokturi',img:'../photo/aksesuari/products/connoisseur_tumsa_bronza_labais_web2.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Fab&Fix "Connoisseur" sērijas espanjolešu tipa loga rokturis ar iebūvētu atslēgas slēdzeni. Piemērots koka un PVC logiem, garums 168 mm.',features:['Apdare: tumša bronza','Puse: labais','Ar atslēgas slēdzeni','Garums: 168 mm','Piemērots koka un PVC logiem']},
  {id:85,name:'Hoppe loga rokturis, titāns',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0600S_US952_titans_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar iebūvētu atslēgas slēdzeni — papildu drošība pret nesankcionētu loga atvēršanu. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: titāns','Ar atslēgas slēdzeni','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:86,name:'Hoppe loga rokturis, antracīts',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0600_US952_antracits_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: antracīts','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:87,name:'Hoppe loga rokturis, balts',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0600_US952_balts_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: balts','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:88,name:'Hoppe loga rokturis, melns',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0600_US952_melns_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: melns','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:89,name:'Hoppe loga rokturis, hroms/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710EVKS_6_F1_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar iebūvētu atslēgas slēdzeni — papildu drošība pret nesankcionētu loga atvēršanu. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: hroms/sudrabs','Puse: labais','Ar atslēgas slēdzeni','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:90,name:'Hoppe loga rokturis, matēts hroms/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710LVK_U71Z_F1_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: matēts hroms/sudrabs','Puse: kreisais','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:91,name:'Hoppe loga rokturis, matēts hroms/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710LVK_U71Z_F1_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: matēts hroms/sudrabs','Puse: labais','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:92,name:'Hoppe loga rokturis, matēts hroms/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710LVK_U71Z_F9_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: matēts hroms/sudrabs','Puse: kreisais','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:93,name:'Hoppe loga rokturis, balts',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710LVK_U71Z_balts_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: balts','Puse: kreisais','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:94,name:'Hoppe loga rokturis, balts',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710LVK_U71Z_balts_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Klasisks loga rokturis logu atvēršanai un ventilācijai. Piemērots PVC un ALU logu profiliem ar standarta stiprinājumu.',features:['Krāsa/apdare: balts','Puse: labais','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:95,name:'Hoppe loga rokturis ar drošības fiksatoru, matēts hroms/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710SV_U26_F1_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar iebūvētu drošības fiksatoru pret roktura pacelšanu un nesankcionētu loga atvēršanu (bez atslēgas). Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: matēts hroms/sudrabs','Ar drošības fiksatoru (bez atslēgas)','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:96,name:'Hoppe loga rokturis, matēts hroms/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710VK_93S_F1_kreisais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar vietu cilindra ieliktnim papildu fiksācijai. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: matēts hroms/sudrabs','Puse: kreisais','Ar vietu cilindra ieliktnim','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:97,name:'Hoppe loga rokturis, matēts hroms/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710VK_93S_F1_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar vietu cilindra ieliktnim papildu fiksācijai. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: matēts hroms/sudrabs','Puse: labais','Ar vietu cilindra ieliktnim','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:98,name:'Hoppe loga rokturis, matēts hroms/sudrabs',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/0710VK_93S_F9_labais_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Loga rokturis ar vietu cilindra ieliktnim papildu fiksācijai. Piemērots PVC un ALU logu profiliem.',features:['Krāsa/apdare: matēts hroms/sudrabs','Puse: labais','Ar vietu cilindra ieliktnim','Zīmols: Hoppe','Piemērots PVC un ALU logiem']},
  {id:99,name:'Hoppe durvju roktura komplekts ar cilindra atveri, vara/rozezelts (matēta bronza)',brand:'Hoppe',cat:'sledzenes',img:'../photo/aksesuari/products/11843391_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Durvju roktura komplekts ar izgriezumu eurocilindram — piemērots ārdurvīm ar atslēgas slēdzeni. Komplektā abi rokturi un stiprinājuma skrūves.',features:['Apdare: vara/rozezelts (matēta bronza)','Ar eurocilindra atveri','Komplektā: 2 rokturi + skrūves','Piemērots ārdurvīm','Zīmols: Hoppe']},
  {id:100,name:'Hoppe durvju roktura komplekts ar WC fiksatoru, tumša bronza',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11843408_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Iekšdurvju roktura komplekts ar iebūvētu griežamo WC/vannas istabas fiksatoru. Piemērots vannas istabas un tualetes durvīm.',features:['Apdare: tumša bronza','Ar WC fiksatoru','Komplektā: 2 rokturi + rozetes','Piemērots vannas/tualetes durvīm','Zīmols: Hoppe']},
  {id:101,name:'Hoppe durvju roktura komplekts, matēts hroms/inox',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11894477_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Durvju roktura pāris (ārpusei un iekšpusei) ārdurvīm vai iekšdurvīm. Bez slēdzenes mehānisma — tikai roktura funkcija.',features:['Krāsa: matēts hroms/inox','Komplektā: 2 rokturi + skrūves','Bez slēdzenes mehānisma','Piemērots ārdurvīm un iekšdurvīm','Zīmols: Hoppe']},
  {id:102,name:'Hoppe durvju roktura komplekts ar cilindra atveri, melns (matēts)',brand:'Hoppe',cat:'sledzenes',img:'../photo/aksesuari/products/11907939_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Durvju roktura komplekts ar izgriezumu eurocilindram — piemērots ārdurvīm ar atslēgas slēdzeni. Komplektā abi rokturi un stiprinājuma skrūves.',features:['Apdare: melns (matēts)','Ar eurocilindra atveri','Komplektā: 2 rokturi + skrūves','Piemērots ārdurvīm','Zīmols: Hoppe']},
  {id:103,name:'Hoppe durvju roktura komplekts ar cilindra atveri, matēts zelts/misiņš',brand:'Hoppe',cat:'sledzenes',img:'../photo/aksesuari/products/11908531_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Durvju roktura komplekts ar izgriezumu eurocilindram — piemērots ārdurvīm ar atslēgas slēdzeni. Komplektā abi rokturi un stiprinājuma skrūves.',features:['Apdare: matēts zelts/misiņš','Ar eurocilindra atveri','Komplektā: 2 rokturi + skrūves','Piemērots ārdurvīm','Zīmols: Hoppe']},
  {id:104,name:'Hoppe durvju roktura komplekts ar WC fiksatoru, matēts zelts/misiņš',brand:'Hoppe',cat:'rokturi',img:'../photo/aksesuari/products/11908609_web.jpg',bg:'#3d6e9c',icon:'rokturis',desc:'Iekšdurvju roktura komplekts ar iebūvētu griežamo WC/vannas istabas fiksatoru. Piemērots vannas istabas un tualetes durvīm.',features:['Apdare: matēts zelts/misiņš','Ar WC fiksatoru','Komplektā: 2 rokturi + rozetes','Piemērots vannas/tualetes durvīm','Zīmols: Hoppe']},

  // Slēdzenes
  {id:16,name:'Fab&Fix durvju rokturis ar atslēgas slēdzeni, matēts hroms/sudrabs',brand:'Fab&Fix',cat:'sledzenes',img:'../photo/aksesuari/products/0D200_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Espanjolešu tipa durvju rokturis ar iebūvētu atslēgas slēdzeni daudzpunktu slēdzenes mehānisma darbināšanai. Garums 168 mm.',features:['Apdare: matēts hroms/sudrabs','Ar atslēgas slēdzeni','Garums: 168 mm','Daudzpunktu slēdzenes darbināšanai']},
  {id:17,name:'Fab&Fix durvju rokturis ar atslēgas slēdzeni, matēts pelēks (anodēts alumīnijs)',brand:'Fab&Fix',cat:'sledzenes',img:'../photo/aksesuari/products/0D201_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Espanjolešu tipa durvju rokturis ar iebūvētu atslēgas slēdzeni daudzpunktu slēdzenes mehānisma darbināšanai. Garums 168 mm.',features:['Apdare: matēts pelēks (anodēts alumīnijs)','Ar atslēgas slēdzeni','Garums: 168 mm','Daudzpunktu slēdzenes darbināšanai']},
  {id:22,name:'FKS durvju roktura komplekts ar cilindra atveri, antracīts/melns (RAL 7016)',brand:'FKS',cat:'sledzenes',img:'../photo/aksesuari/products/1005B%20Ral%207016_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Durvju roktura komplekts ar izgriezumu eurocilindram — piemērots ārdurvīm ar atslēgas slēdzeni. Komplektā abi rokturi un stiprinājuma skrūves.',features:['Apdare: antracīts/melns (RAL 7016)','Ar eurocilindra atveri','Komplektā: 2 rokturi + skrūves','Piemērots ārdurvīm','Zīmols: FKS']},
  {id:23,name:'FKS durvju roktura komplekts ar cilindra atveri, balts/brūns',brand:'FKS',cat:'sledzenes',img:'../photo/aksesuari/products/1005B%20bal_bru_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Durvju roktura komplekts ar izgriezumu eurocilindram — piemērots ārdurvīm ar atslēgas slēdzeni. Komplektā abi rokturi un stiprinājuma skrūves.',features:['Apdare: balts/brūns','Ar eurocilindra atveri','Komplektā: 2 rokturi + skrūves','Piemērots ārdurvīm','Zīmols: FKS']},
  {id:24,name:'FKS durvju roktura komplekts ar cilindra atveri, balts',brand:'FKS',cat:'sledzenes',img:'../photo/aksesuari/products/1005B%20bal_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Durvju roktura komplekts ar izgriezumu eurocilindram — piemērots ārdurvīm ar atslēgas slēdzeni. Komplektā abi rokturi un stiprinājuma skrūves.',features:['Apdare: balts','Ar eurocilindra atveri','Komplektā: 2 rokturi + skrūves','Piemērots ārdurvīm','Zīmols: FKS']},
  {id:25,name:'FKS durvju roktura komplekts ar cilindra atveri, brūns',brand:'FKS',cat:'sledzenes',img:'../photo/aksesuari/products/1005B%20br_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Durvju roktura komplekts ar izgriezumu eurocilindram — piemērots ārdurvīm ar atslēgas slēdzeni. Komplektā abi rokturi un stiprinājuma skrūves.',features:['Apdare: brūns','Ar eurocilindra atveri','Komplektā: 2 rokturi + skrūves','Piemērots ārdurvīm','Zīmols: FKS']},
  {id:37,name:'Hoppe durvju roktura komplekts ar cilindra atveri, vara/rozezelts (matēta bronza)',brand:'Hoppe',cat:'sledzenes',img:'../photo/aksesuari/products/11647589_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Durvju roktura komplekts ar izgriezumu eurocilindram — piemērots ārdurvīm ar atslēgas slēdzeni. Komplektā abi rokturi un stiprinājuma skrūves.',features:['Apdare: vara/rozezelts (matēta bronza)','Ar eurocilindra atveri','Komplektā: 2 rokturi + skrūves','Piemērots ārdurvīm','Zīmols: Hoppe']},
  {id:49,name:'Hoppe durvju roktura komplekts ar cilindra atveri, sudrabs/matēts hroms',brand:'Hoppe',cat:'sledzenes',img:'../photo/aksesuari/products/11758156_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Durvju roktura komplekts ar izgriezumu eurocilindram — piemērots ārdurvīm ar atslēgas slēdzeni. Komplektā abi rokturi un stiprinājuma skrūves.',features:['Apdare: sudrabs/matēts hroms','Ar eurocilindra atveri','Komplektā: 2 rokturi + skrūves','Piemērots ārdurvīm','Zīmols: Hoppe']},
  {id:50,name:'Hoppe durvju roktura komplekts ar cilindra atveri, melns/antracīts (matēts)',brand:'Hoppe',cat:'sledzenes',img:'../photo/aksesuari/products/11758168_web.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Durvju roktura komplekts ar izgriezumu eurocilindram — piemērots ārdurvīm ar atslēgas slēdzeni. Komplektā abi rokturi un stiprinājuma skrūves.',features:['Apdare: melns/antracīts (matēts)','Ar eurocilindra atveri','Komplektā: 2 rokturi + skrūves','Piemērots ārdurvīm','Zīmols: Hoppe']},
  {id:70,name:'Hermai durvju roktura komplekts ar cilindra atveri, matēts hroms/inox',brand:'Hermai',cat:'sledzenes',img:'../photo/aksesuari/products/SICHL.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Durvju roktura komplekts ar izgriezumu eurocilindram — piemērots ārdurvīm ar atslēgas slēdzeni. Komplektā abi rokturi un stiprinājuma skrūves.',features:['Apdare: matēts hroms/inox','Ar eurocilindra atveri','Komplektā: 2 rokturi + skrūves','Piemērots ārdurvīm','Zīmols: Hermai']},
  {id:71,name:'Hermai durvju roktura komplekts ar cilindra atveri, matēts hroms/niķelis',brand:'Hermai',cat:'sledzenes',img:'../photo/aksesuari/products/SICHR.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Durvju roktura komplekts ar izgriezumu eurocilindram — piemērots ārdurvīm ar atslēgas slēdzeni. Komplektā abi rokturi un stiprinājuma skrūves.',features:['Apdare: matēts hroms/niķelis','Ar eurocilindra atveri','Komplektā: 2 rokturi + skrūves','Piemērots ārdurvīm','Zīmols: Hermai']},
  {id:72,name:'Hermai durvju roktura komplekts ar cilindra atveri, pulēts zelts/misiņš',brand:'Hermai',cat:'sledzenes',img:'../photo/aksesuari/products/SICZR.jpg',bg:'#3a4a6a',icon:'sledzene',desc:'Durvju roktura komplekts ar izgriezumu eurocilindram — piemērots ārdurvīm ar atslēgas slēdzeni. Komplektā abi rokturi un stiprinājuma skrūves.',features:['Apdare: pulēts zelts/misiņš','Ar eurocilindra atveri','Komplektā: 2 rokturi + skrūves','Piemērots ārdurvīm','Zīmols: Hermai']},

  // Eņģes
  {id:53,name:'greenteQ eņģes vāciņš, balts',brand:'greenteQ',cat:'enges',img:'../photo/aksesuari/products/2172745859_web.jpg',bg:'#7b5e3a',icon:'enge',desc:'Dekoratīvs vāciņš loga vai durvju eņģes nosegšanai. Uzliek ar klikšķi, stiprina ar 2 skrūvēm.',features:['Krāsa: balts','Izmērs: 82×49×21 mm','Stiprinājums: 2 skrūves','greenteQ (VBH) zīmols']},
  {id:54,name:'greenteQ eņģes vāciņš, melns/antracīts',brand:'greenteQ',cat:'enges',img:'../photo/aksesuari/products/2172745861_web.jpg',bg:'#7b5e3a',icon:'enge',desc:'Dekoratīvs vāciņš loga vai durvju eņģes nosegšanai. Uzliek ar klikšķi, stiprina ar 2 skrūvēm.',features:['Krāsa: melns/antracīts','Izmērs: 82×49×21 mm','Stiprinājums: 2 skrūves','greenteQ (VBH) zīmols']},
  {id:55,name:'greenteQ eņģes vāciņš, sudrabs/alumīnijs',brand:'greenteQ',cat:'enges',img:'../photo/aksesuari/products/2172745863_web.jpg',bg:'#7b5e3a',icon:'enge',desc:'Dekoratīvs vāciņš loga vai durvju eņģes nosegšanai. Uzliek ar klikšķi, stiprina ar 2 skrūvēm.',features:['Krāsa: sudrabs/alumīnijs','Izmērs: 82×49×21 mm','Stiprinājums: 2 skrūves','greenteQ (VBH) zīmols']},

  // Hermētiķi
  {id:56,name:'Lakma hermētiķis, bezkrāsains',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/Bezkrasains.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silikona hermētiķis logu un durvju montāžas šuvju noblīvēšanai. Augsta UV un laikapstākļu izturība, paliek elastīgs pēc sacietēšanas.',features:['Krāsa: bezkrāsains','Silikona hermētiķis','UV un laikapstākļu izturīgs','Lakma ražojums']},
  {id:57,name:'Lakma hermētiķis, bezkrāsains',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/Bezkrasains_280.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silikona hermētiķis logu un durvju montāžas šuvju noblīvēšanai. Augsta UV un laikapstākļu izturība, paliek elastīgs pēc sacietēšanas.',features:['Krāsa: bezkrāsains','Silikona hermētiķis','UV un laikapstākļu izturīgs','Lakma ražojums']},
  {id:58,name:'Lakma hermētiķis, bēšs (RAL 1011)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL1011.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silikona hermētiķis logu un durvju montāžas šuvju noblīvēšanai. Augsta UV un laikapstākļu izturība, paliek elastīgs pēc sacietēšanas.',features:['Krāsa: bēšs (RAL 1011)','Silikona hermētiķis','UV un laikapstākļu izturīgs','Lakma ražojums']},
  {id:59,name:'Lakma hermētiķis, ziloņkaula (RAL 1014)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL1014.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silikona hermētiķis logu un durvju montāžas šuvju noblīvēšanai. Augsta UV un laikapstākļu izturība, paliek elastīgs pēc sacietēšanas.',features:['Krāsa: ziloņkaula (RAL 1014)','Silikona hermētiķis','UV un laikapstākļu izturīgs','Lakma ražojums']},
  {id:60,name:'Lakma hermētiķis, antracīts (RAL 7016)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL7016.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silikona hermētiķis logu un durvju montāžas šuvju noblīvēšanai. Augsta UV un laikapstākļu izturība, paliek elastīgs pēc sacietēšanas.',features:['Krāsa: antracīts (RAL 7016)','Silikona hermētiķis','UV un laikapstākļu izturīgs','Lakma ražojums']},
  {id:61,name:'Lakma hermētiķis, putekļu pelēks (RAL 7037)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL7037.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silikona hermētiķis logu un durvju montāžas šuvju noblīvēšanai. Augsta UV un laikapstākļu izturība, paliek elastīgs pēc sacietēšanas.',features:['Krāsa: putekļu pelēks (RAL 7037)','Silikona hermētiķis','UV un laikapstākļu izturīgs','Lakma ražojums']},
  {id:62,name:'Lakma hermētiķis, logu pelēks (RAL 7040)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL7040.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silikona hermētiķis logu un durvju montāžas šuvju noblīvēšanai. Augsta UV un laikapstākļu izturība, paliek elastīgs pēc sacietēšanas.',features:['Krāsa: logu pelēks (RAL 7040)','Silikona hermētiķis','UV un laikapstākļu izturīgs','Lakma ražojums']},
  {id:63,name:'Lakma hermētiķis, oker brūns (RAL 8001)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL8001.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silikona hermētiķis logu un durvju montāžas šuvju noblīvēšanai. Augsta UV un laikapstākļu izturība, paliek elastīgs pēc sacietēšanas.',features:['Krāsa: oker brūns (RAL 8001)','Silikona hermētiķis','UV un laikapstākļu izturīgs','Lakma ražojums']},
  {id:64,name:'Lakma hermētiķis, māla brūns (RAL 8003)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL8003.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silikona hermētiķis logu un durvju montāžas šuvju noblīvēšanai. Augsta UV un laikapstākļu izturība, paliek elastīgs pēc sacietēšanas.',features:['Krāsa: māla brūns (RAL 8003)','Silikona hermētiķis','UV un laikapstākļu izturīgs','Lakma ražojums']},
  {id:65,name:'Lakma hermētiķis, riekstu brūns (RAL 8011)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL8011.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silikona hermētiķis logu un durvju montāžas šuvju noblīvēšanai. Augsta UV un laikapstākļu izturība, paliek elastīgs pēc sacietēšanas.',features:['Krāsa: riekstu brūns (RAL 8011)','Silikona hermētiķis','UV un laikapstākļu izturīgs','Lakma ražojums']},
  {id:66,name:'Lakma hermētiķis, kastaņbrūns (RAL 8015)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL8015.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silikona hermētiķis logu un durvju montāžas šuvju noblīvēšanai. Augsta UV un laikapstākļu izturība, paliek elastīgs pēc sacietēšanas.',features:['Krāsa: kastaņbrūns (RAL 8015)','Silikona hermētiķis','UV un laikapstākļu izturīgs','Lakma ražojums']},
  {id:67,name:'Lakma hermētiķis, šokolādes brūns (RAL 8017)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL8017.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silikona hermētiķis logu un durvju montāžas šuvju noblīvēšanai. Augsta UV un laikapstākļu izturība, paliek elastīgs pēc sacietēšanas.',features:['Krāsa: šokolādes brūns (RAL 8017)','Silikona hermētiķis','UV un laikapstākļu izturīgs','Lakma ražojums']},
  {id:68,name:'Lakma hermētiķis, pelēkbrūns (RAL 8019)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL8019.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silikona hermētiķis logu un durvju montāžas šuvju noblīvēšanai. Augsta UV un laikapstākļu izturība, paliek elastīgs pēc sacietēšanas.',features:['Krāsa: pelēkbrūns (RAL 8019)','Silikona hermētiķis','UV un laikapstākļu izturīgs','Lakma ražojums']},
  {id:69,name:'Lakma hermētiķis, dziļmelns (RAL 9005)',brand:'Lakma',cat:'hermetiki',img:'../photo/aksesuari/products/RAL9005.jpg',bg:'#2e7e7e',icon:'hermetikis',desc:'Silikona hermētiķis logu un durvju montāžas šuvju noblīvēšanai. Augsta UV un laikapstākļu izturība, paliek elastīgs pēc sacietēšanas.',features:['Krāsa: dziļmelns (RAL 9005)','Silikona hermētiķis','UV un laikapstākļu izturīgs','Lakma ražojums']},

  // Apkope
  {id:1,name:'Brevis ventilācijas vārsts (balts)',brand:'Brevis',cat:'apkope',img:'../photo/aksesuari/products/008064_web.jpg',bg:'#5a4a8a',icon:'apkope',desc:'Logu ventilācijas vārsts ar slīdošu vāku un pagriežamu regulēšanas mehānismu svaiga gaisa pieplūdei telpā. Uzstādāms loga rāmī, neietekmējot siltumizolāciju.',features:['Garums ~395 mm, sprauga ~345 mm','Krāsa: balts','Regulējams ar pagriežamu rokturi','Piemērots PVC un ALU logu profiliem']},
  {id:2,name:'Brevis ventilācijas vārsts (brūns)',brand:'Brevis',cat:'apkope',img:'../photo/aksesuari/products/008065_web.jpg',bg:'#5a4a8a',icon:'apkope',desc:'Logu ventilācijas vārsts ar slīdošu vāku un pagriežamu regulēšanas mehānismu svaiga gaisa pieplūdei telpā. Uzstādāms loga rāmī, neietekmējot siltumizolāciju.',features:['Garums ~395 mm, sprauga ~345 mm','Krāsa: brūns','Regulējams ar pagriežamu rokturi','Piemērots PVC un ALU logu profiliem']},
  {id:3,name:'Brevis ventilācijas vārsts (tumši brūns)',brand:'Brevis',cat:'apkope',img:'../photo/aksesuari/products/008066_web.jpg',bg:'#5a4a8a',icon:'apkope',desc:'Logu ventilācijas vārsts ar slīdošu vāku un pagriežamu regulēšanas mehānismu svaiga gaisa pieplūdei telpā. Uzstādāms loga rāmī, neietekmējot siltumizolāciju.',features:['Garums ~395 mm, sprauga ~345 mm','Krāsa: tumši brūns','Regulējams ar pagriežamu rokturi','Piemērots PVC un ALU logu profiliem']},
  {id:4,name:'Brevis ventilācijas vārsts (antracīts/melnpelēks)',brand:'Brevis',cat:'apkope',img:'../photo/aksesuari/products/024709_web.jpg',bg:'#5a4a8a',icon:'apkope',desc:'Logu ventilācijas vārsts ar slīdošu vāku un pagriežamu regulēšanas mehānismu svaiga gaisa pieplūdei telpā. Uzstādāms loga rāmī, neietekmējot siltumizolāciju.',features:['Garums ~395 mm, sprauga ~345 mm','Krāsa: antracīts/melnpelēks','Regulējams ar pagriežamu rokturi','Piemērots PVC un ALU logu profiliem']},
  {id:5,name:'Brevis ventilācijas vārsts (brūns/vara tonis)',brand:'Brevis',cat:'apkope',img:'../photo/aksesuari/products/032309_web.jpg',bg:'#5a4a8a',icon:'apkope',desc:'Logu ventilācijas vārsts ar slīdošu vāku un pagriežamu regulēšanas mehānismu svaiga gaisa pieplūdei telpā. Uzstādāms loga rāmī, neietekmējot siltumizolāciju.',features:['Garums ~395 mm, sprauga ~345 mm','Krāsa: brūns/vara tonis','Regulējams ar pagriežamu rokturi','Piemērots PVC un ALU logu profiliem']}

];
